# Generated by Django 2.2 on 2019-05-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_activate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activate',
        ),
    ]
