# Generated by Django 2.2 on 2019-05-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alternative_user', models.IntegerField(default=-1, verbose_name='代わりに入る人')),
                ('date', models.DateField()),
                ('shift_zone', models.CharField(max_length=15)),
                ('comment', models.TextField(default='なし', max_length=200)),
                ('is_settled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Absence_user', models.IntegerField(default=-1, verbose_name='休む人')),
                ('date', models.DateField()),
                ('shift_zone', models.CharField(max_length=15)),
                ('comment', models.TextField(default='なし', max_length=200)),
                ('is_settled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_Sat', models.CharField(max_length=15)),
                ('shift_Sun', models.CharField(max_length=15)),
                ('is_board', models.BooleanField(default=False)),
            ],
        ),
    ]
