# Generated by Django 2.2 on 2019-04-22 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_Sat', models.CharField(max_length=15)),
                ('shift_Sun', models.CharField(max_length=15)),
                ('is_board', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Absence_user', models.IntegerField(blank=True, verbose_name='休む人')),
                ('date', models.DateField()),
                ('shift_zone', models.CharField(max_length=15)),
                ('is_settled', models.BooleanField(default=False)),
                ('Alternative_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='代わりに入る人')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alternative_user', models.IntegerField(blank=True, verbose_name='代わりに入る人')),
                ('date', models.DateField()),
                ('shift_zone', models.CharField(max_length=15)),
                ('is_settled', models.BooleanField(default=False)),
                ('Absence_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='休む人')),
            ],
        ),
    ]
